// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6UOyMyhbYPRqvbi8LwVZc18yfL5IHv4s',
    appId: '1:970721470332:web:8602af1786970bf22f66f9',
    messagingSenderId: '970721470332',
    projectId: 'orsa-602cb',
    authDomain: 'orsa-602cb.firebaseapp.com',
    storageBucket: 'orsa-602cb.appspot.com',
    measurementId: 'G-HX4H4M4HPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqrhXV1xMz2qUnJ7Xvtk4OHMzseBgvFoE',
    appId: '1:970721470332:android:1ebf98ff06a1b2572f66f9',
    messagingSenderId: '970721470332',
    projectId: 'orsa-602cb',
    storageBucket: 'orsa-602cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5nVxDLr9Y9-STclXJFWm18QgE8Mp0QyA',
    appId: '1:970721470332:ios:5d60b65e09e1aae62f66f9',
    messagingSenderId: '970721470332',
    projectId: 'orsa-602cb',
    storageBucket: 'orsa-602cb.appspot.com',
    iosBundleId: 'com.example.gradproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5nVxDLr9Y9-STclXJFWm18QgE8Mp0QyA',
    appId: '1:970721470332:ios:5d60b65e09e1aae62f66f9',
    messagingSenderId: '970721470332',
    projectId: 'orsa-602cb',
    storageBucket: 'orsa-602cb.appspot.com',
    iosBundleId: 'com.example.gradproject',
  );
}
